<?xml version='1.0' encoding='UTF-8'?>
<definitions name="FTP" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/FTP/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/ftp/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/FTP/" xmlns:opaque="http://xmlns.oracle.com/pcbpel/adapter/opaque/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
   <plt:partnerLinkType name="Put_plt">
      <plt:role name="Put_role">
         <plt:portType name="tns:Put_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <types>
      <schema targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/opaque/" xmlns="http://www.w3.org/2001/XMLSchema">
         <element name="opaqueElement" type="base64Binary"/>
      </schema>
   </types>
   <message name="Put_msg">
      <part name="opaque" element="opaque:opaqueElement"/>
   </message>
   <portType name="Put_ptt">
      <operation name="Put">
         <input message="tns:Put_msg"/>
      </operation>
   </portType>
</definitions>
