<?xml version='1.0' encoding='UTF-8'?>
<definitions name="FTP_ASCII" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/FTP_ASCII/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/ftp/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/FTP_ASCII/" xmlns:imp1="http://xmlns.oracle.com/datafile" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
   <plt:partnerLinkType name="Put_plt">
      <plt:role name="Put_role">
         <plt:portType name="tns:Put_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <types>
      <schema targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/FTP_ASCII/" xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/datafile" schemaLocation="xsd/datafile.xsd"/>
      </schema>
   </types>
   <message name="V2C_msg">
      <part name="V2C" element="imp1:V2C"/>
   </message>
   <portType name="Put_ptt">
      <operation name="Put">
         <input message="tns:V2C_msg"/>
      </operation>
   </portType>
</definitions>
